// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CleanupItems() {
  return window['go']['main']['App']['CleanupItems']();
}

export function ExecuteClean(arg1) {
  return window['go']['main']['App']['ExecuteClean'](arg1);
}

export function GetCacheLocation() {
  return window['go']['main']['App']['GetCacheLocation']();
}

export function GetCleanHistory() {
  return window['go']['main']['App']['GetCleanHistory']();
}

export function GetDirChildren(arg1) {
  return window['go']['main']['App']['GetDirChildren'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetTopFiles() {
  return window['go']['main']['App']['GetTopFiles']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function LoadSnapshot(arg1) {
  return window['go']['main']['App']['LoadSnapshot'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RecyclePath(arg1) {
  return window['go']['main']['App']['RecyclePath'](arg1);
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function ResetCacheLocation() {
  return window['go']['main']['App']['ResetCacheLocation']();
}

export function RestoreHistory(arg1) {
  return window['go']['main']['App']['RestoreHistory'](arg1);
}

export function SetCacheLocation(arg1) {
  return window['go']['main']['App']['SetCacheLocation'](arg1);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}
