// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScan():Promise<void>;

export function CleanupItems():Promise<Array<main.CleanItem>>;

export function Dependencies():Promise<Array<main.DepInfo>>;

export function ExecuteClean(arg1:Array<string>):Promise<Array<main.CleanResult>>;

export function GetCacheLocation():Promise<main.CacheLocation>;

export function GetCleanHistory():Promise<Array<main.HistoryEntry>>;

export function GetDirChildren(arg1:string):Promise<Array<main.DirChild>>;

export function GetDrives():Promise<Array<main.DriveInfo>>;

export function GetTopFiles():Promise<Array<main.TopFileEntry>>;

export function IsAdmin():Promise<boolean>;

export function IsScanning():Promise<boolean>;

export function LoadSnapshot(arg1:string):Promise<main.SnapshotInfo>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function QuitApp():Promise<void>;

export function RecyclePath(arg1:string):Promise<void>;

export function RequestElevation():Promise<boolean>;

export function ResetCacheLocation():Promise<main.CacheLocation>;

export function RestoreHistory(arg1:number):Promise<main.RestoreResult>;

export function SetCacheLocation(arg1:string):Promise<main.CacheLocation>;

export function StartScan(arg1:string,arg2:number):Promise<void>;
